# Generated by Django 6.0.1 on 2026-02-13 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت به تومان')),
                ('duration_days', models.IntegerField(verbose_name='مدت زمان اشتراک (روز)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اشتراک کاربر', 'verbose_name_plural': 'اشتراک\u200cهای کاربران'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال است؟'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.plan', verbose_name='پلن خریداری شده'),
        ),
    ]
