# Generated by Django 6.0.1 on 2026-02-14 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan_alter_subscription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات (اختیاری)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه Authority زرین\u200cپال'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پیگیری زرین\u200cپال (Ref ID)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ندارد', 'ندارد'), ('فعال', 'فعال'), ('منقضی', 'منقضی')], default='ندارد', max_length=10, verbose_name='وضعیت اشتراک'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(verbose_name='مدت زمان اشتراک (روز)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
