# Generated by Django 6.0.1 on 2026-04-09 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image_url', models.URLField(blank=True, help_text='لینک مستقیم تصویر', max_length=500, verbose_name='لینک تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلاید首页',
                'verbose_name_plural': 'اسلایدها',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'گزینه', 'verbose_name_plural': 'گزینه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'آزمون', 'verbose_name_plural': 'آزمون\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'verbose_name': 'تلاش کاربر', 'verbose_name_plural': 'تلاش\u200cهای کاربر'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'پاسخ کاربر', 'verbose_name_plural': 'پاسخ\u200cهای کاربر'},
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='تکمیل شده؟'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='آزمون'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt', verbose_name='تلاش'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.choice', verbose_name='گزینه انتخاب شده'),
        ),
    ]
