# Generated by Django 6.0.1 on 2026-04-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteVisit',
        ),
    ]
