# Generated by Django 6.0.1 on 2026-04-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_delete_sitevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('visits_today', models.PositiveIntegerField(default=0)),
                ('unique_visitors_today', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
