# Generated by Django 6.0.1 on 2026-04-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_homeslider_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='image_url',
        ),
        migrations.AddField(
            model_name='homeslider',
            name='image',
            field=models.FileField(blank=True, upload_to='sliders/', verbose_name='تصویر'),
        ),
    ]
