# Generated by Django 6.0.1 on 2026-04-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_homeslider_image_url_homeslider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='آزمون فعال باشد؟'),
        ),
    ]
