# Generated by Django 6.0.1 on 2026-04-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_visitorstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorstats',
            options={'ordering': ['-date'], 'verbose_name': 'آمار بازدید', 'verbose_name_plural': 'آمار بازدیدها'},
        ),
    ]
