# Generated by Django 6.0.1 on 2026-04-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_visitorstats_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بازدید IP',
                'verbose_name_plural': 'بازدیدهای IP',
                'unique_together': {('ip_address', 'date')},
            },
        ),
    ]
