# Generated by Django 6.0.1 on 2026-04-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_remove_visitorstats_visits_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorstats',
            name='visits_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
