# Generated by Django 6.0.1 on 2026-04-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_visitorstats_visits_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorstats',
            name='visits_today',
        ),
    ]
