# Generated by Django 6.0.1 on 2026-05-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_remove_visitorstats_visits_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='عکس/گیف')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('position', models.CharField(choices=[('left', 'سمت چپ'), ('right', 'سمت راست')], max_length=20, verbose_name='موقعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بنر تبلیغ',
                'verbose_name_plural': 'بنرهای تبلیغ',
            },
        ),
    ]
