# Generated by Django 6.0.1 on 2026-05-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_adbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='position',
            field=models.CharField(choices=[('left', ' تبلیغ اولی'), ('right', 'تبلیغ دومی ')], max_length=20, verbose_name='موقعیت'),
        ),
    ]
