# Generated by Django 6.0.1 on 2026-06-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_adbanner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, upload_to='sliders/', verbose_name='تصویر'),
        ),
    ]
