# Generated by Django 6.0.1 on 2026-07-03 05:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_alter_homeslider_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adbanner',
            options={'verbose_name': 'تبلیغ', 'verbose_name_plural': 'تبلیغات'},
        ),
        migrations.AlterModelOptions(
            name='homeslider',
            options={'ordering': ['order'], 'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'آزمون', 'verbose_name_plural': 'آزمون\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'verbose_name': 'تلاش آزمون', 'verbose_name_plural': 'تلاش\u200cهای آزمون'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'پاسخ کاربر', 'verbose_name_plural': 'پاسخ\u200cهای کاربران'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='image',
            field=models.ImageField(upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='position',
            field=models.CharField(choices=[('left', 'سمت چپ'), ('right', 'سمت راست')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='پاسخ صحیح'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='آزمون'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='زمان آزمون'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال باشد؟'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.choice'),
        ),
    ]
